indent-width = 2
line-length = 120
preview = true
required-version = '>=0.16.10'
respect-gitignore = false
target-version = 'py313'

[format]
docstring-code-format = true
quote-style = 'single'
preview = true

[lint]
select = ['ALL']
ignore = [
  'missing-trailing-comma',
  'missing-copyright-notice',
  'undocumented-public-module',
  'undocumented-public-class',
  'undocumented-public-method',
  'undocumented-public-function',
  'undocumented-public-package',
  'undocumented-magic-method',
  'undocumented-public-nested-class',
  'undocumented-public-init',
  'indentation-with-invalid-multiple',
  'indentation-with-invalid-multiple-comment',
  'logging-f-string',
  'bad-quotes-docstring',
  'T20',
]
preview = true

[lint.flake8-quotes]
docstring-quotes = 'single'
inline-quotes = 'single'

[lint.pydocstyle]
convention = 'google'
