[colors.primary]
background = '#000000'

[env]
TERM = 'xterm-256color'

[font]
size = 20

[font.glyph_offset]
x = -1
y = -4

[font.normal]
family = 'JetBrainsMono NF'

[font.offset]
x = -2
y = -7

[[mouse.bindings]]
action = 'Paste'
mouse = 'Right'

[selection]
save_to_clipboard = true

[window]
decorations = 'none'
opacity = 0.8
option_as_alt = 'Both'
startup_mode = 'Maximized'
